package ru.javawebinar.topjava.web;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import ru.javawebinar.topjava.model.MealTo;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class MealServlet extends HttpServlet {
    private static final Logger log = LoggerFactory.getLogger(MealServlet.class);

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
//        super.doGet(req, resp);
        req.setCharacterEncoding("UTF-8");
        req.setAttribute("mealList", meals);
        resp.setContentType("text/html;charset=utf-8");
//        resp.sendRedirect("meals.jsp");
        getServletContext().getRequestDispatcher("/meals.jsp").forward(req, resp);
    }

    private static final List<MealTo> meals = new ArrayList<MealTo>() {
        {
            add(new MealTo(LocalDateTime.now(), "Артишоки", 45, true));
            add(new MealTo(LocalDateTime.now(), "Баклажаны", 28, true));
            add(new MealTo(LocalDateTime.now(), "Зелёный горошек", 93, true));
            add(new MealTo(LocalDateTime.now(), "Зелёный горошек консервированный", 41, true));
            add(new MealTo(LocalDateTime.now(), "Кабачки", 22, true));
            add(new MealTo(LocalDateTime.now(), "Капуста белокочанная", 23, true));
            add(new MealTo(LocalDateTime.now(), "Капуста брокколи", 33, false));
            add(new MealTo(LocalDateTime.now(), "Капуста брюссельская", 12, true));
            add(new MealTo(LocalDateTime.now(), "Капуста квашеная", 20, true));
            add(new MealTo(LocalDateTime.now(), "Капуста китайская", 16, true));
            add(new MealTo(LocalDateTime.now(), "Капуста краснокочанная", 27, true));
            add(new MealTo(LocalDateTime.now(), "Капуста кольраби", 26, true));
            add(new MealTo(LocalDateTime.now(), "Капуста цветная", 18, true));
            add(new MealTo(LocalDateTime.now(), "Картофель отварной", 60, true));
            add(new MealTo(LocalDateTime.now(), "Кукуруза", 103, true));
            add(new MealTo(LocalDateTime.now(), "Лук зелёный", 20, true));
            add(new MealTo(LocalDateTime.now(), "Лук репчатый", 45, true));
            add(new MealTo(LocalDateTime.now(), "Морковь", 34, true));
            add(new MealTo(LocalDateTime.now(), "Огурцы свежие", 15, true));
            add(new MealTo(LocalDateTime.now(), "Огурцы соленые", 8, true));
            add(new MealTo(LocalDateTime.now(), "Перец сладкий", 19, true));
            add(new MealTo(LocalDateTime.now(), "Петрушка", 23, true));
            add(new MealTo(LocalDateTime.now(), "Помидоры", 15, true));
            add(new MealTo(LocalDateTime.now(), "Ревень", 16, true));
            add(new MealTo(LocalDateTime.now(), "Редис", 18, true));
            add(new MealTo(LocalDateTime.now(), "Редька", 25, false));
            add(new MealTo(LocalDateTime.now(), "Репа", 25, true));
            add(new MealTo(LocalDateTime.now(), "Салат", 15, true));
            add(new MealTo(LocalDateTime.now(), "Свёкла", 44, true));
            add(new MealTo(LocalDateTime.now(), "Сельдерей листовой", 21, true));
            add(new MealTo(LocalDateTime.now(), "Сельдерея корнеплоды", 38, true));
            add(new MealTo(LocalDateTime.now(), "Тыква", 24, true));
            add(new MealTo(LocalDateTime.now(), "Укроп", 30, true));
            add(new MealTo(LocalDateTime.now(), "Фасоль стручковая", 31, true));
            add(new MealTo(LocalDateTime.now(), "Хрен", 49, true));
            add(new MealTo(LocalDateTime.now(), "Цветная капуста", 28, true));
            add(new MealTo(LocalDateTime.now(), "Чеснок", 60, true));
            add(new MealTo(LocalDateTime.now(), "Шпинат", 17, true));
            add(new MealTo(LocalDateTime.now(), "Щавель", 28, true));
            add(new MealTo(LocalDateTime.now(), "Абрикосы", 49, true));
            add(new MealTo(LocalDateTime.now(), "Авокадо", 204, false));
            add(new MealTo(LocalDateTime.now(), "Айва", 30, true));
            add(new MealTo(LocalDateTime.now(), "Алыча", 38, true));
            add(new MealTo(LocalDateTime.now(), "Ананас", 44, true));
            add(new MealTo(LocalDateTime.now(), "Апельсин", 45, true));
            add(new MealTo(LocalDateTime.now(), "Арбуз", 40, true));
            add(new MealTo(LocalDateTime.now(), "Бананы", 90, true));
            add(new MealTo(LocalDateTime.now(), "Брусника", 45, true));
            add(new MealTo(LocalDateTime.now(), "Виноград", 70, true));
            add(new MealTo(LocalDateTime.now(), "Вишня", 25, true));
            add(new MealTo(LocalDateTime.now(), "Голубика", 37, true));
            add(new MealTo(LocalDateTime.now(), "Гранат", 52, false));
            add(new MealTo(LocalDateTime.now(), "Грейпфрут", 35, true));
            add(new MealTo(LocalDateTime.now(), "Груша", 42, true));
            add(new MealTo(LocalDateTime.now(), "Дыня", 45, true));
            add(new MealTo(LocalDateTime.now(), "Ежевика", 32, true));
            add(new MealTo(LocalDateTime.now(), "Земляника", 48, true));
            add(new MealTo(LocalDateTime.now(), "Инжир", 56, true));
            add(new MealTo(LocalDateTime.now(), "Киви", 50, true));
            add(new MealTo(LocalDateTime.now(), "Кизил", 41, true));
            add(new MealTo(LocalDateTime.now(), "Клубника", 35, true));
            add(new MealTo(LocalDateTime.now(), "Клюква", 33, true));
            add(new MealTo(LocalDateTime.now(), "Крыжовник", 48, true));
            add(new MealTo(LocalDateTime.now(), "Лимон", 30, true));
            add(new MealTo(LocalDateTime.now(), "Малина", 45, true));
            add(new MealTo(LocalDateTime.now(), "Мандарин", 41, true));
            add(new MealTo(LocalDateTime.now(), "Облепиха", 30, true));
            add(new MealTo(LocalDateTime.now(), "Персики", 45, true));
            add(new MealTo(LocalDateTime.now(), "Рябина садовая", 81, true));
            add(new MealTo(LocalDateTime.now(), "Рябина черноплодная", 54, true));
            add(new MealTo(LocalDateTime.now(), "Слива", 44, true));
            add(new MealTo(LocalDateTime.now(), "Смородина", 43, true));
            add(new MealTo(LocalDateTime.now(), "Черешня", 53, true));
            add(new MealTo(LocalDateTime.now(), "Черника", 44, false));
            add(new MealTo(LocalDateTime.now(), "Яблоки", 45, true));
            add(new MealTo(LocalDateTime.now(), "Семечки", 580, true));
            add(new MealTo(LocalDateTime.now(), "Орехи Грецкие", 650, true));
            add(new MealTo(LocalDateTime.now(), "Орехи земляные (арахис)",470, true));
            add(new MealTo(LocalDateTime.now(), "Орехи Кедровые", 620, true));
            add(new MealTo(LocalDateTime.now(), "Миндаль", 600, true));
            add(new MealTo(LocalDateTime.now(), "Фисташки", 620, true));
            add(new MealTo(LocalDateTime.now(), "Фундук", 705, true));
            add(new MealTo(LocalDateTime.now(), "Изюм", 280, true));
            add(new MealTo(LocalDateTime.now(), "Инжир", 290, true));
            add(new MealTo(LocalDateTime.now(), "Кишмиш", 310, true));
            add(new MealTo(LocalDateTime.now(), "Курага", 293, true));
            add(new MealTo(LocalDateTime.now(), "Урюк", 297, false));
            add(new MealTo(LocalDateTime.now(), "Финики", 290, true));
            add(new MealTo(LocalDateTime.now(), "Чернослив", 220, true));
            add(new MealTo(LocalDateTime.now(), "Яблоки", 210, true));
            add(new MealTo(LocalDateTime.now(), "Яйцо куриное 1шт.",65, true));
            add(new MealTo(LocalDateTime.now(), "Яичный порошок", 540, true));
            add(new MealTo(LocalDateTime.now(), "Грибы белые", 25, true));
            add(new MealTo(LocalDateTime.now(), "Грибы белые сушёные", 210, true));
            add(new MealTo(LocalDateTime.now(), "Грибы вареные", 25, true));
            add(new MealTo(LocalDateTime.now(), "Грибы в сметане", 230, true));
            add(new MealTo(LocalDateTime.now(), "Грибы жаренные", 165, true));
            add(new MealTo(LocalDateTime.now(), "Опята", 20, true));
            add(new MealTo(LocalDateTime.now(), "Подберезовики", 30, true));
            add(new MealTo(LocalDateTime.now(), "Подосиновики", 30, true));
            add(new MealTo(LocalDateTime.now(), "Баранки", 312, true));
            add(new MealTo(LocalDateTime.now(), "Лепёшка ржаная", 375, true));
            add(new MealTo(LocalDateTime.now(), "Сдобная выпечка", 300, true));
            add(new MealTo(LocalDateTime.now(), "Сушки, пряники", 330, false));
            add(new MealTo(LocalDateTime.now(), "Сухари пшеничные", 330, true));
            add(new MealTo(LocalDateTime.now(), "Хлеб Дарницкий", 206, true));
            add(new MealTo(LocalDateTime.now(), "Хлеб пшеничный (белый)",265, true));
            add(new MealTo(LocalDateTime.now(), "Хлеб ржаной (черный)",210, true));
            add(new MealTo(LocalDateTime.now(), "Ацидофилин (3,2% жирности)",58, true));
            add(new MealTo(LocalDateTime.now(), "Брынза коровья", 260, true));
            add(new MealTo(LocalDateTime.now(), "Йогурт (15%)",51, true));
            add(new MealTo(LocalDateTime.now(), "Кефир жирный", 60, true));
            add(new MealTo(LocalDateTime.now(), "Кефир (1% жирности)",38, true));
            add(new MealTo(LocalDateTime.now(), "Кефир обезжиренный", 30, true));
            add(new MealTo(LocalDateTime.now(), "Молоко (3,2% жирности)",60, true));
            add(new MealTo(LocalDateTime.now(), "Молоко коровье цельное", 68, true));
            add(new MealTo(LocalDateTime.now(), "Молого сгущенное с сахаром", 324, true));
            add(new MealTo(LocalDateTime.now(), "Молоко сухое", 470, true));
            add(new MealTo(LocalDateTime.now(), "Мороженое сливочное", 220, true));
            add(new MealTo(LocalDateTime.now(), "Простокваша", 59, true));
            add(new MealTo(LocalDateTime.now(), "Ряженка", 85, true));
            add(new MealTo(LocalDateTime.now(), "Сливки (10% жирности)",120, true));
            add(new MealTo(LocalDateTime.now(), "Сливки (20% жирности)",300, true));
            add(new MealTo(LocalDateTime.now(), "Сметана (10%)",	115, true));
            add(new MealTo(LocalDateTime.now(), "Сметана (20%)", 210, true));
            add(new MealTo(LocalDateTime.now(), "Сырки творожные", 380, true));
            add(new MealTo(LocalDateTime.now(), "Сырковая масса", 207, true));
            add(new MealTo(LocalDateTime.now(), "Творог (18% жирности)",226, true));
            add(new MealTo(LocalDateTime.now(), "Творог нежирный", 80, true));
            add(new MealTo(LocalDateTime.now(), "Творог со сметаной", 260, true));
            add(new MealTo(LocalDateTime.now(), "Сыр голландский", 357, true));
            add(new MealTo(LocalDateTime.now(), "Сыр Гауда", 384, true));
            add(new MealTo(LocalDateTime.now(), "Сыр Ламбер", 377, true));
            add(new MealTo(LocalDateTime.now(), "Сыр Пармезан", 330, true));
            add(new MealTo(LocalDateTime.now(), "Сыр Российский", 371, true));
            add(new MealTo(LocalDateTime.now(), "Сыр колбасный", 268, true));
            add(new MealTo(LocalDateTime.now(), "Сыр Рокфор", 352, true));
            add(new MealTo(LocalDateTime.now(), "Сыр Честер", 398, true));
            add(new MealTo(LocalDateTime.now(), "Сыр Швейцарский", 335, true));
            add(new MealTo(LocalDateTime.now(), "Горох Зелёный", 280, true));
            add(new MealTo(LocalDateTime.now(), "Мука Пшеничная", 348, true));
            add(new MealTo(LocalDateTime.now(), "Мука Ржаная", 347, true));
            add(new MealTo(LocalDateTime.now(), "Крупа Гречневая ядрица", 346, true));
            add(new MealTo(LocalDateTime.now(), "Крупа манная", 340, true));
            add(new MealTo(LocalDateTime.now(), "Крупа овсяная", 374, true));
            add(new MealTo(LocalDateTime.now(), "Крупа перловая", 342, true));
            add(new MealTo(LocalDateTime.now(), "Крупа пшеничная", 352, true));
            add(new MealTo(LocalDateTime.now(), "Крупа пшенная", 335, true));
            add(new MealTo(LocalDateTime.now(), "Крупа ячневая", 343, true));
            add(new MealTo(LocalDateTime.now(), "Кукурузные хлопья", 369, true));
            add(new MealTo(LocalDateTime.now(), "Макаронные изделия", 350, true));
            add(new MealTo(LocalDateTime.now(), "Мюсли", 370, true));
            add(new MealTo(LocalDateTime.now(), "Овсяные хлопья", 305, true));
            add(new MealTo(LocalDateTime.now(), "Пшено", 351, true));
            add(new MealTo(LocalDateTime.now(), "Рис", 337, true));
            add(new MealTo(LocalDateTime.now(), "Соя", 395, true));
            add(new MealTo(LocalDateTime.now(), "Фасоль", 328, true));
            add(new MealTo(LocalDateTime.now(), "Чечевица", 310, true));
            add(new MealTo(LocalDateTime.now(), "Ячменные хлопья", 315, true));
            add(new MealTo(LocalDateTime.now(), "Грудинка", 533, true));
            add(new MealTo(LocalDateTime.now(), "Окорок", 375, true));
            add(new MealTo(LocalDateTime.now(), "Отбивная на косточке", 380, true));
            add(new MealTo(LocalDateTime.now(), "Лопатка", 380, true));
            add(new MealTo(LocalDateTime.now(), "Спинная часть", 459, true));
            add(new MealTo(LocalDateTime.now(), "Говядина тушеная", 180, true));
            add(new MealTo(LocalDateTime.now(), "Говядина жареная", 170, true));
            add(new MealTo(LocalDateTime.now(), "Говяжий фарш", 118, true));
            add(new MealTo(LocalDateTime.now(), "Грудинка", 405, true));
            add(new MealTo(LocalDateTime.now(), "Лопатка", 208, true));
            add(new MealTo(LocalDateTime.now(), "Мозги", 124, true));
            add(new MealTo(LocalDateTime.now(), "Нежирное жаркое", 200, true));
            add(new MealTo(LocalDateTime.now(), "Оковалок", 380, true));
            add(new MealTo(LocalDateTime.now(), "Окорок", 308, true));
            add(new MealTo(LocalDateTime.now(), "Печень", 87, true));
            add(new MealTo(LocalDateTime.now(), "Почки", 59, true));
            add(new MealTo(LocalDateTime.now(), "Ребра", 446, true));
            add(new MealTo(LocalDateTime.now(), "Сердце", 82, true));
            add(new MealTo(LocalDateTime.now(), "Филе стейк",189, true));
            add(new MealTo(LocalDateTime.now(), "Филе ростбиф",381, true));
            add(new MealTo(LocalDateTime.now(), "Нежирное жаркое", 184, true));
            add(new MealTo(LocalDateTime.now(), "Окорок", 543, true));
            add(new MealTo(LocalDateTime.now(), "Отбивная на косточке", 537, true));
            add(new MealTo(LocalDateTime.now(), "Печень", 108, true));
            add(new MealTo(LocalDateTime.now(), "Плечо", 593, true));
            add(new MealTo(LocalDateTime.now(), "Почки", 80, true));
            add(new MealTo(LocalDateTime.now(), "Свиная ножка", 431, true));
            add(new MealTo(LocalDateTime.now(), "Сердце", 90, true));
            add(new MealTo(LocalDateTime.now(), "Филе", 264, true));
            add(new MealTo(LocalDateTime.now(), "Шейка", 552, true));
            add(new MealTo(LocalDateTime.now(), "Шницель", 252, true));
            add(new MealTo(LocalDateTime.now(), "Язык", 208, true));
            add(new MealTo(LocalDateTime.now(), "Грудинка", 213, true));
            add(new MealTo(LocalDateTime.now(), "Ножка", 161, true));
            add(new MealTo(LocalDateTime.now(), "Окорок", 155, true));
            add(new MealTo(LocalDateTime.now(), "Отбивная на косточке", 188, true));
            add(new MealTo(LocalDateTime.now(), "Спинная часть", 210, true));
            add(new MealTo(LocalDateTime.now(), "Филе", 158, true));
            add(new MealTo(LocalDateTime.now(), "Шницель", 162, true));
            add(new MealTo(LocalDateTime.now(), "Гусь", 390, true));
            add(new MealTo(LocalDateTime.now(), "Дикая птица, в среднем", 108, true));
            add(new MealTo(LocalDateTime.now(), "Индейка", 200, true));
            add(new MealTo(LocalDateTime.now(), "Индюк", 230, true));
            add(new MealTo(LocalDateTime.now(), "Зайчатина", 124, true));
            add(new MealTo(LocalDateTime.now(), "Колбаса вареная", 250, true));
            add(new MealTo(LocalDateTime.now(), "Колбаса полукопченая", 380, true));
            add(new MealTo(LocalDateTime.now(), "Корейка", 430, true));
            add(new MealTo(LocalDateTime.now(), "Крольчатина", 115, true));
            add(new MealTo(LocalDateTime.now(), "Курица вареная", 135, true));
            add(new MealTo(LocalDateTime.now(), "Курица жареная", 210, true));
            add(new MealTo(LocalDateTime.now(), "Утка", 405, true));
            add(new MealTo(LocalDateTime.now(), "Фазан", 143, true));
            add(new MealTo(LocalDateTime.now(), "Цыплята", 156, true));
            add(new MealTo(LocalDateTime.now(), "Ветчина", 365, true));
            add(new MealTo(LocalDateTime.now(), "Вяленое мясо", 264, true));
            add(new MealTo(LocalDateTime.now(), "Колбаса Диабетическая", 254, true));
            add(new MealTo(LocalDateTime.now(), "Колбаса Диетическая", 170, true));
            add(new MealTo(LocalDateTime.now(), "Колбаса Докторская", 260, true));
            add(new MealTo(LocalDateTime.now(), "Колбаса Любительская", 291, true));
            add(new MealTo(LocalDateTime.now(), "Колбаса Кровяная", 452, true));
            add(new MealTo(LocalDateTime.now(), "Колбаса Украинская", 404, true));
            add(new MealTo(LocalDateTime.now(), "Полукопченая Краковская", 466, true));
            add(new MealTo(LocalDateTime.now(), "Полукопченая Минская", 259, true));
            add(new MealTo(LocalDateTime.now(), "Полукопченая Полтавская", 417, true));
            add(new MealTo(LocalDateTime.now(), "Полукопченая Украинская", 376, true));
            add(new MealTo(LocalDateTime.now(), "Колбаса копченая", 507, true));
            add(new MealTo(LocalDateTime.now(), "Паштет из печени", 314, true));
            add(new MealTo(LocalDateTime.now(), "Колбаса языковая", 215, true));
            add(new MealTo(LocalDateTime.now(), "Сало", 248, true));
            add(new MealTo(LocalDateTime.now(), "Салями", 560, true));
            add(new MealTo(LocalDateTime.now(), "Сардельки", 147, true));
            add(new MealTo(LocalDateTime.now(), "Сервелат", 484, true));
            add(new MealTo(LocalDateTime.now(), "Сосиски", 204, true));
            add(new MealTo(LocalDateTime.now(), "Шпик", 215, true));
            add(new MealTo(LocalDateTime.now(), "Горбуша", 147, true));
            add(new MealTo(LocalDateTime.now(), "Икра зернистая", 250, true));
            add(new MealTo(LocalDateTime.now(), "Икра кетовая", 245, true));
            add(new MealTo(LocalDateTime.now(), "Икра минтая", 130, true));
            add(new MealTo(LocalDateTime.now(), "Кальмар", 75, true));
            add(new MealTo(LocalDateTime.now(), "Камбала", 90, true));
            add(new MealTo(LocalDateTime.now(), "Карп", 87, true));
            add(new MealTo(LocalDateTime.now(), "Карп жареный", 145, true));
            add(new MealTo(LocalDateTime.now(), "Кета", 157, true));
            add(new MealTo(LocalDateTime.now(), "Консервы рыбные в масле", 320, true));
            add(new MealTo(LocalDateTime.now(), "Консервы рыбные в собственном соку", 120, true));
            add(new MealTo(LocalDateTime.now(), "Креветки", 85, true));
            add(new MealTo(LocalDateTime.now(), "Крабы", 70, true));
            add(new MealTo(LocalDateTime.now(), "Лещ", 100, true));
            add(new MealTo(LocalDateTime.now(), "Лососина жареная", 145, true));
            add(new MealTo(LocalDateTime.now(), "Лососина копченая", 385, true));
            add(new MealTo(LocalDateTime.now(), "Макрурус", 60, true));
            add(new MealTo(LocalDateTime.now(), "Мидии", 72, true));
            add(new MealTo(LocalDateTime.now(), "Минтай", 70, true));
            add(new MealTo(LocalDateTime.now(), "Мойва", 157, true));
            add(new MealTo(LocalDateTime.now(), "Морская капуста", 16, true));
            add(new MealTo(LocalDateTime.now(), "Навага", 44, true));
            add(new MealTo(LocalDateTime.now(), "нАЛИМ", 81, true));
            add(new MealTo(LocalDateTime.now(), "Окунь морской", 95, true));
            add(new MealTo(LocalDateTime.now(), "Окунь речной", 82, true));
            add(new MealTo(LocalDateTime.now(), "Омар", 82, true));
            add(new MealTo(LocalDateTime.now(), "Печень трески", 613, true));
            add(new MealTo(LocalDateTime.now(), "Раки", 75, true));
            add(new MealTo(LocalDateTime.now(), "Салака", 98, true));
            add(new MealTo(LocalDateTime.now(), "Севрюга", 137, true));
            add(new MealTo(LocalDateTime.now(), "Сельдь атлантическая", 57, true));
            add(new MealTo(LocalDateTime.now(), "Семга", 219, true));
            add(new MealTo(LocalDateTime.now(), "Сиг", 144, true));
            add(new MealTo(LocalDateTime.now(), "Скумбрия", 153, true));
            add(new MealTo(LocalDateTime.now(), "Сом", 154, true));
            add(new MealTo(LocalDateTime.now(), "Ставрида", 119, true));
            add(new MealTo(LocalDateTime.now(), "Стерлядь", 320, true));
            add(new MealTo(LocalDateTime.now(), "Судак", 72, true));
            add(new MealTo(LocalDateTime.now(), "Треска", 59, true));
            add(new MealTo(LocalDateTime.now(), "Трепанг", 35, true));
            add(new MealTo(LocalDateTime.now(), "Тунец", 296, true));
            add(new MealTo(LocalDateTime.now(), "Угорь речной", 598, true));
            add(new MealTo(LocalDateTime.now(), "Форель", 208, true));
            add(new MealTo(LocalDateTime.now(), "Хек", 86, true));
            add(new MealTo(LocalDateTime.now(), "Шпроты в масле", 250, true));
            add(new MealTo(LocalDateTime.now(), "Щука", 72, true));
            add(new MealTo(LocalDateTime.now(), "Жир говяжий топленый", 871, true));
            add(new MealTo(LocalDateTime.now(), "Жир гусиный", 930, true));
            add(new MealTo(LocalDateTime.now(), "Жир топлёный", 930, true));
            add(new MealTo(LocalDateTime.now(), "Маргарин сливочный", 745, true));
            add(new MealTo(LocalDateTime.now(), "Маргарин бутербродный", 670, true));
            add(new MealTo(LocalDateTime.now(), "Маргарин для выпечки", 675, true));
            add(new MealTo(LocalDateTime.now(), "Масло арахисовое", 895, true));
            add(new MealTo(LocalDateTime.now(), "Масло кукурузное", 900, true));
            add(new MealTo(LocalDateTime.now(), "Масло оливковое", 824, true));
            add(new MealTo(LocalDateTime.now(), "Масло подсолнечное", 900, true));
            add(new MealTo(LocalDateTime.now(), "Масло сливочное", 750, true));
            add(new MealTo(LocalDateTime.now(), "Масло соевое", 900, true));
            add(new MealTo(LocalDateTime.now(), "Масло топлёное", 885, true));
            add(new MealTo(LocalDateTime.now(), "Кетчуп", 80, true));
            add(new MealTo(LocalDateTime.now(), "Майонез", 625, true));
            add(new MealTo(LocalDateTime.now(), "Майонез лёгкий", 260, true));
            add(new MealTo(LocalDateTime.now(), "Апельсиновый сок", 123, true));
            add(new MealTo(LocalDateTime.now(), "Грейпфрутовый сок без сахара", 75, true));
            add(new MealTo(LocalDateTime.now(), "Кола", 110, true));
            add(new MealTo(LocalDateTime.now(), "Кофе без молока и сахара", 0, true));
            add(new MealTo(LocalDateTime.now(), "Лимонад", 123, true));
            add(new MealTo(LocalDateTime.now(), "Минеральная вода", 0, true));
            add(new MealTo(LocalDateTime.now(), "Морковный сок", 68, true));
            add(new MealTo(LocalDateTime.now(), "Овощной напиток", 60, true));
            add(new MealTo(LocalDateTime.now(), "Сок из красной смородины", 125, true));
            add(new MealTo(LocalDateTime.now(), "Сок из черной смородины", 138, true));
            add(new MealTo(LocalDateTime.now(), "Яблочный сок", 118, true));
            add(new MealTo(LocalDateTime.now(), "Чай без сахара", 0, true));
            add(new MealTo(LocalDateTime.now(), "Вино белое", 80, true));
            add(new MealTo(LocalDateTime.now(), "Вино красное", 74, true));
            add(new MealTo(LocalDateTime.now(), "Вино яблочное", 37, true));
            add(new MealTo(LocalDateTime.now(), "Виски", 240, true));
            add(new MealTo(LocalDateTime.now(), "Вишневая наливка", 300, true));
            add(new MealTo(LocalDateTime.now(), "Водка", 275, true));
            add(new MealTo(LocalDateTime.now(), "Джин", 33, true));
            add(new MealTo(LocalDateTime.now(), "Ликер", 325, true));
            add(new MealTo(LocalDateTime.now(), "Коньяк", 250, true));
            add(new MealTo(LocalDateTime.now(), "Пиво", 45, true));
            add(new MealTo(LocalDateTime.now(), "Сливянка", 120, true));
            add(new MealTo(LocalDateTime.now(), "Сидр", 40, true));
            add(new MealTo(LocalDateTime.now(), "Шампанское сухое", 85, true));
            add(new MealTo(LocalDateTime.now(), "Шнапс", 200, true));
            add(new MealTo(LocalDateTime.now(), "Вафли с фруктовыми начинками ", 342, true));
            add(new MealTo(LocalDateTime.now(), "Вафли с жиросодержащими начинками", 530, true));
            add(new MealTo(LocalDateTime.now(), "Варенье", 294, true));
            add(new MealTo(LocalDateTime.now(), "Драже фруктовое", 384, true));
            add(new MealTo(LocalDateTime.now(), "Зефир", 300, true));
            add(new MealTo(LocalDateTime.now(), "Ирис", 387, true));
            add(new MealTo(LocalDateTime.now(), "Какао", 416, true));
            add(new MealTo(LocalDateTime.now(), "Карамель", 296, true));
            add(new MealTo(LocalDateTime.now(), "Конфеты, глазированные шоколадом", 396, true));
            add(new MealTo(LocalDateTime.now(), "Мед", 310, true));
            add(new MealTo(LocalDateTime.now(), "Мармелад", 296, true));
            add(new MealTo(LocalDateTime.now(), "Пастила", 305, true));
            add(new MealTo(LocalDateTime.now(), "Повидло", 270, true));
            add(new MealTo(LocalDateTime.now(), "Пирожное слоеное с кремом ", 544, true));
            add(new MealTo(LocalDateTime.now(), "Пирожное слоеное с яблоком ", 454, true));
            add(new MealTo(LocalDateTime.now(), "Пирожное бисквитное с фруктовой начинкой ", 344, true));
            add(new MealTo(LocalDateTime.now(), "Сахар", 380, true));
            add(new MealTo(LocalDateTime.now(), "Торт бисквитный с фруктовой начинкой ", 386, true));
            add(new MealTo(LocalDateTime.now(), "Торт миндальный", 524, true));
            add(new MealTo(LocalDateTime.now(), "Халва тахинная", 510, true));
            add(new MealTo(LocalDateTime.now(), "Халва подсолнечная", 516, true));
            add(new MealTo(LocalDateTime.now(), "Шоколад горький", 540, true));
            add(new MealTo(LocalDateTime.now(), "Шоколад молочный", 548, true));
        }
    };
}
